// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fakpilfbxszzrcvjdrpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZha3BpbGZieHN6enJjdmpkcnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjQ1NzYsImV4cCI6MjA2MTEwMDU3Nn0.QHHcUAVcKPLBTwQiwF63_pkqjSY683tNRa-EXV34-mY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);